image: i386/ubuntu:16.04

build-image:
 stage: build
 tags:
   - ECE391
 script:
   - apt update
   - apt install python-software-properties
   - apt install software-properties-common
   - apt update
   - apt install gcc-4.8
   - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
   - apt install make
